project:
  type: website
  resources:
    - linkml
  render:
    - "*.qmd"
    - "!junk/"

website:
  title: "QQV"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: primer.qmd
        text: Primer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

syntax-definitions:
  - turtle.xml